### PR TITLE
Call presented UIViewController lifecycle methods from UINavigationController

### LINKED ISSUE #341: UINavigationController does not call `viewWillAppear`
## Current behavior
When using a UINavigationController as the root view controller, you can see the Android-style navigation bar at the top but the content is completely black and doesn't seem to show the root view controller that I set inside the UINavigationController.

## Expected behavior
Seeing a normal UINavigationController but with the root view controller actually being shown instead of having a completely black screen below the navigation bar.

## Steps to reproduce
1. Use the sample project and set the root view controller of the window inside AppDelegate.swift to a UINavigationController that has ViewController as its root view controller.
2. Run it on any supported OS (got the same weird results with Android, macOS Monterey and iOS 15.1).

## Screenshots

Screen Shot 2021-11-07 at 18 39 49

## Environment
- Device: Xiaomi A2
- OS: Android Q
- UIKit Version: Latest commit (f8cb41875a3d7a6fa726170e48c68cf0498bd5ac)

### PR DESCRIPTION
**Pull request by ephemer**
Fixes #341 

**Type of change:** Bug fix

## Motivation (current vs expected behavior)

As reported in #341, UINavigationController does not work as expected. This is because `viewWillAppear` (etc.) are never called there. I have added a call to `viewWillAppear` and `viewDidAppear`, but there are probably other lifecycle methods that are currently not being called.

## Please check if the PR fulfills these requirements
- [x] Self-review: I am confident this is the simplest and clearest way to achieve the expected behaviour
- [x] There are no dependencies on other PRs or I have linked dependencies through Zenhub
- [x] The commit messages are clean and understandable
- [ ] Tests for the changes have been added (for bug fixes / features)

### CODE REVIEW

**Comment by rikner** [comment]
Hey @ephemer ! 
I reproduced the issue this way (AppDelegate.swift):
```
let viewController = ViewController()
let navigationController = UINavigationController(rootViewController: viewController)
window?.rootViewController = navigationController
```
The PR seems to fix the issue, but I realized that the BackButton does not seem to work. Tapping it has no effect. Using the hardware button (or actually the screen gesture in my case) works.

https://user-images.githubusercontent.com/2410252/141165039-abe0a397-7ffe-4aea-afa6-3855764a983f.mp4

**Comment by ephemer** [comment]
Hey @rikner, thanks a lot for testing this!

I disabled the back button specifically in this PR because it should not do anything when the `UINavigationController` is at root position. If the back button still "works" we need to fix that too :)

**Comment by rikner** [comment]
> Hey @rikner, thanks a lot for testing this!
> 
> I disabled the back button specifically in this PR because it should not do anything when the `UINavigationController` is at root position. If we dismiss the rootViewController the app will be "dead" forever. If the hardware back button still "works" we need to fix that too :)

Ah ok I see. Apparently I have no idea what the expected behaviour is. Are you looking into disabling the Hardware Button?

**Comment by ephemer** [comment]
@rikner the hardware back button should work in general, but the "back button" on a UINavigationController should not do anything if there is only one view on the stack _and_ that UINavigationController is the application's `rootViewController`

**Comment by rikner** [comment]
> @rikner the hardware back button should work in general, but the "back button" on a UINavigationController should not do anything if there is only one view on the navigation stack _and_ that UINavigationController is the application's `rootViewController`

Ok, yeah I get that. But then shouldn't we make sure that in this special case the hardware back button does not send the App into the void like seen in the video? Or would that be an issue for a seperate PR?

**Comment by ephemer** [comment]
Yep:

> If the hardware back button still "works" we need to fix that too :)

File: Sources/UINavigationController.swift [hunk 1]
```diff
@@ -62,6 +65,11 @@ open class UINavigationController: UIViewController {
     }
 
     open override func dismiss(animated: Bool, completion: (() -> Void)? = nil) {
+        if self === UIApplication.shared.keyWindow?.rootViewController {
+            completion?()
+            return
+        }
```
Comment (ephemer) [inline Sources/UINavigationController.swift:71]: @rikner this should fix the issue you were seeing

File: samples/getting-started/DemoApp/AppDelegate.swift [hunk 2]
```diff
@@ -19,10 +19,9 @@ final class AppDelegate: UIResponder, UIApplicationDelegate {
     ) -> Bool {
 
         window = UIWindow()
-        window?.rootViewController = ViewController()
+        window?.rootViewController = UINavigationController(rootViewController: ViewController())
```
Comment (ephemer) [inline samples/getting-started/DemoApp/AppDelegate.swift:22]: @michaelknoch any objections to this?

File: Sources/UINavigationController.swift (hunk 1 above)
Comment (ephemer) [reply Sources/UINavigationController.swift]: I tested this in the Mac App (Esc has the same effect as the physical back button on Android) and it works as expected (as in, it doesn't do anything) 👍🏼

**Review by michaelknoch — APPROVED** [review]
looks good to me!

**Comment by ephemer** [comment]
@rikner @michaelknoch would appreciate a(nother) review on this

File: samples/getting-started/DemoApp/AppDelegate.swift (hunk 2 above)
Comment (michaelknoch) [reply samples/getting-started/DemoApp/AppDelegate.swift:22]: nope, makes sense I think

**Comment by michaelknoch** [comment]
oops, CI doesn't like the change @ephemer 😄 
https://app.circleci.com/pipelines/github/flowkey/UIKit-cross-platform/151/workflows/202a524e-10dc-4ce7-9862-0da1201f167d/jobs/1453

**Comment by ephemer** [comment]
@michaelknoch `UIViewControllerTests.testMemoryLeakInNavigationController` seems very suspicious ;) I will check it out thanks

**Comment by ephemer** [comment]
ah, it's because `navigationController!.dismiss(animated: false)` will now only work if it's not the root view controller, which is desired behaviour. I will fix it

File: Sources/UINavigationController.swift (hunk 1 above)
Comment (rikner) [reply Sources/UINavigationController.swift]: yes, can confirm 👍

**Review by rikner — APPROVED** [review]
